### ISSUE TITLE
Crash when descending into NamedTuple constructor

### ISSUE THREAD

**Issue by Zentrik** [JuliaDebug/Cthulhu.jl#474] opened 2023-06-19 10:40 UTC
```julia
julia> @descend NamedTuple()
NamedTuple() in Core at boot.jl:601
601 NamedTuple()::Core.Const(NamedTuple()) = NamedTuple::Type{NamedTuple}{(),Tuple::Type{Tuple}{}::Type{Tuple{}}}::Type{NamedTuple{(), Tuple{}}}(())
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
Toggles: [w]arn, [h]ide type-stable statements, [t]ype annotations, [s]yntax highlight for Source/LLVM/Native.
Show: [S]ource code, [A]ST, [T]yped code, [L]LVM IR, [N]ative code
Actions: [E]dit source code, [R]evise and redisplay
 • NamedTuple::Type{NamedTuple}{(),Tuple::Type{Tuple}{}::Type{Tuple{}}}::Type{NamedTuple{(), Tuple{}}}(())
   ↩
ERROR: KeyError: key :T not found
Stacktrace:
  [1] getindex
    @ .\dict.jl:498 [inlined]
  [2] map_ssas_to_source(src::Core.CodeInfo, rootnode::JuliaSyntax.SyntaxNode, Δline::Int64)
    @ TypedSyntax C:\Users\gag\.julia\packages\TypedSyntax\vbZHi\src\node.jl:681
  [3] tsn_and_mappings(m::Method, src::Core.CodeInfo, rt::Any, sourcetext::SubString{String}, lineno::Int64; warn::Bool, strip_macros::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ TypedSyntax C:\Users\gag\.julia\packages\TypedSyntax\vbZHi\src\node.jl:47
  [4] tsn_and_mappings(m::Method, src::Core.CodeInfo, rt::Any; warn::Bool, strip_macros::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ TypedSyntax C:\Users\gag\.julia\packages\TypedSyntax\vbZHi\src\node.jl:34
  [5] get_typed_sourcetext(mi::Core.MethodInstance, src::Core.CodeInfo, rt::Any; warn::Bool)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\reflection.jl:346
  [6] find_callsites(interp::Cthulhu.CthulhuInterpreter, CI::Core.CodeInfo, stmt_infos::Vector{Any}, mi::Core.MethodInstance, slottypes::Vector{Any}, optimize::Bool, annotate_source::Bool)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\reflection.jl:28
  [7] _descend(term::REPL.Terminals.TTYTerminal, interp::Cthulhu.CthulhuInterpreter, curs::Cthulhu.CthulhuCursor; override::Nothing, debuginfo::Cthulhu.DInfo.DebugInfo, optimize::Bool, interruptexc::Bool, iswarn::Bool, hide_type_stable::Bool, verbose::Nothing, remarks::Bool, with_effects::Bool, inline_cost::Bool, type_annotations::Bool, annotate_source::Bool)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:458
  [8] _descend(term::REPL.Terminals.TTYTerminal, interp::Cthulhu.CthulhuInterpreter, curs::Cthulhu.CthulhuCursor; override::Nothing, debuginfo::Symbol, optimize::Bool, interruptexc::Bool, iswarn::Bool, hide_type_stable::Bool, verbose::Nothing, remarks::Bool, with_effects::Bool, inline_cost::Bool, type_annotations::Bool, annotate_source::Bool)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:591
  [9] _descend(term::REPL.Terminals.TTYTerminal, interp::Cthulhu.CthulhuInterpreter, mi::Core.MethodInstance; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:iswarn,), Tuple{Bool}}})
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:724
 [10] _descend(term::REPL.Terminals.TTYTerminal, args::Any; interp::Core.Compiler.NativeInterpreter, kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:iswarn,), Tuple{Bool}}})
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:740
 [11] __descend_with_error_handling(args::Any; terminal::Any, kwargs::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:207
 [12] _descend_with_error_handling(f::Any, argtypes::Any; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:iswarn,), Tuple{Bool}}})
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:196
 [13] descend_code_typed(::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:154
 [14] descend_code_typed(::Any, ::Any)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\vJrGb\src\Cthulhu.jl:154
 [15] top-level scope
    @ REPL[4]:1
```

Crash occurs when descending into the only callsite.

**Comment by timholy** [comment] 2023-08-04 13:33
Closing as a duplicate of https://github.com/timholy/CodeTracking.jl/issues/115

**Closed by timholy** 2023-08-04 13:33 UTC
