### ISSUE TITLE
Crashes while traversing Flux ADs

### ISSUE THREAD

**Issue by jmulcahy** [JuliaDebug/Cthulhu.jl#58] opened 2019-08-16 01:02 UTC
As mentioned here: https://github.com/FluxML/Flux.jl/issues/828. Cthulhu is crashing while trying to traverse through Flux's ADs (both Tracker and Zygote). Here is an example with Tracker. The same error occurs for Zygote if you use Flux's Zygote branch. The interface for Tracker and Zygote are pretty similar, so the crash is probably triggered somewhere in there.

```
julia> using Flux, Cthulhu

julia> function test_tracker_big()
              t = ones(Float32, 200, 200, 1, 1)
              f = Conv((1, 1), 1=>1)
              ps = params(f)
              Flux.Tracker.gradient(() -> sum(f(t)), ps)
              end
test_tracker_big (generic function with 1 method)

julia> @descend test_tracker_big()

│ ─ %-1  = invoke test_tracker_big()::Tracker.Grads
CodeInfo(
    @ REPL[1]:2 within `test_tracker_big'
   ┌ @ array.jl:449 within `ones' @ array.jl:452
   │┌ @ boot.jl:414 within `Type'
1 ─││ %1  = $(Expr(:foreigncall, :(:jl_new_array), Array{Float32,4}, svec(Any, Any), :(:ccall), 2, Array{Float32,4}, (200, 200, 1, 1)))::Array{Float32,4}
│  │└
│  │ %2  = invoke Base.fill!(%1::Array{Float32,4}, 1.0f0::Float32)::Array{Float32,4}
│  └
│   @ REPL[1]:3 within `test_tracker_big'
│   %3  = Main.Conv::Core.Compiler.Const(Conv, false)
│  ┌ @ /Users/johnmulcahy/.julia/packages/Flux/qXNjB/src/layers/conv.jl:44 within `Type'
│  │ %4  = Flux.identity::typeof(identity)
│  │ @ /Users/johnmulcahy/.julia/packages/Flux/qXNjB/src/layers/conv.jl:44 within `Type' @ /Users/johnmulcahy/.julia/packages/Flux/qXNjB/src/layers/conv.jl:44
│  │ %5  = invoke Flux.:(#Conv#80)(Flux.glorot_uniform::Function, 1::Int64, 0::Int64, 1::Int64, %3::Type, (1, 1)::Tuple{Int64,Int64}, $(QuoteNode(1 => 1))::Pair{Int64,Int64}, %4::Function)::Conv{_1,_2,typeof(identity),_3,TrackedArray{…,Array{Float32,1}}} where _3 where _2 where _1
│  └
│   @ REPL[1]:4 within `test_tracker_big'
│   %6  = (Main.params)(%5)::Tracker.Params
│   @ REPL[1]:5 within `test_tracker_big'
│   %7  = Main.:(##7#8)::Core.Compiler.Const(getfield(Main, Symbol("##7#8")), false)
│   %8  = (Core.typeof)(%5)::Type{#s70} where #s70<:Conv{_1,_2,typeof(identity),_3,TrackedArray{…,Array{Float32,1}}} where _3 where _2 where _1
│   %9  = (Core.apply_type)(%7, Array{Float32,4}, %8)::Type{getfield(Main, Symbol("##7#8")){Array{Float32,4},_1}} where _1
│   %10 = %new(%9, %2, %5)::getfield(Main, Symbol("##7#8")){Array{Float32,4},_1} where _1
│  ┌ @ /Users/johnmulcahy/.julia/packages/Tracker/RRYy6/src/back.jl:164 within `gradient'
│  │ %11 = invoke Tracker.:(#gradient#24)(false::Bool, Tracker.gradient::Function, %10::Function, %6::Tracker.Params)::Tracker.Grads
│  └
└──       return %11
)
Select a call to descend into or ↩ to ascend. [q]uit.
Toggles: [o]ptimize, [w]arn, [d]ebuginfo, [s]yntax highlight for LLVM/Native.
Show: [L]LVM IR, [N]ative code
Advanced: dump [P]arams cache.

   %2  = invoke fill!(::Array{Float32,4},::Float32)::Array{Float32,4}
   %5  = invoke #Conv#80(::Function,::Int64,::Int64,::Int64,::Type,::Tuple{Int64,Int64},::Pair{Int64,Int64},::Function)
   %6  = invoke params(::Conv{_1,_2,typeof(identity),_3,TrackedArray{…,Array{Float32,1}}} where _3 where _2 where _1)::Tracker.Params
 • %11  = invoke #gradient#24(::Bool,::Function,::Function,::Tracker.Params)::Tracker.Grads
   ↩

│ ─ %-1  = invoke #gradient#24(::Bool,::Function,::Function,::Tracker.Params)::Tracker.Grads
CodeInfo(
    @ /Users/johnmulcahy/.julia/packages/Tracker/RRYy6/src/back.jl:164 within `#gradient#24'
1 ─      goto #3 if not nest
2 ─ %2 = (getfield)(xs, 1)::Tracker.Params
│   %3 = invoke Tracker.gradient_nested(_4::Function, %2::Tracker.Params)::Tracker.Grads
└──      return %3
3 ─ %5 = (getfield)(xs, 1)::Tracker.Params
│   %6 = (Tracker.gradient_)(f, %5)::Tracker.Grads
└──      return %6
)
Select a call to descend into or ↩ to ascend. [q]uit.
Toggles: [o]ptimize, [w]arn, [d]ebuginfo, [s]yntax highlight for LLVM/Native.
Show: [L]LVM IR, [N]ative code
Advanced: dump [P]arams cache.

   %3  = invoke gradient_nested(::Function,::Tracker.Params)::Tracker.Grads
 • %6  = invoke gradient_(::Function,::Tracker.Params)::Tracker.Grads
   ↩
ERROR: BoundsError: attempt to access 22-element Array{Int64,1} at index [0]
Stacktrace:
 [1] getindex(::Array{Int64,1}, ::Int64) at ./array.jl:729
 [2] Core.Compiler.IncrementalCompact(::Core.Compiler.IRCode, ::Bool) at ./compiler/ssair/ir.jl:510
 [3] dce!(::Core.CodeInfo, ::Core.MethodInstance) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/reflection.jl:161
 [4] preprocess_ci!(::Core.CodeInfo, ::Core.MethodInstance, ::Bool) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/reflection.jl:191
 [5] #_descend#38(::Bool, ::Core.Compiler.Params, ::Bool, ::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:debuginfo,),Tuple{Symbol}}}, ::Function, ::Core.MethodInstance) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:122
 [6] #_descend#38(::Bool, ::Core.Compiler.Params, ::Bool, ::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:debuginfo,),Tuple{Symbol}}}, ::Function, ::Core.MethodInstance) at ./none:0
 [7] #_descend at ./none:0 [inlined]
 [8] #_descend#38(::Bool, ::Core.Compiler.Params, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Core.MethodInstance) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:177
 [9] #_descend at ./none:0 [inlined]
 [10] #_descend#43(::Core.Compiler.Params, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:iswarn,),Tuple{Bool}}}, ::Function, ::Any, ::Any) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:211
 [11] #_descend at ./none:0 [inlined]
 [12] #_descend_with_error_handling#37(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:iswarn,),Tuple{Bool}}}, ::Function, ::Function, ::Any) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:88
 [13] #_descend_with_error_handling at ./none:0 [inlined]
 [14] #descend_code_typed#35 at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:62 [inlined]
 [15] descend_code_typed(::Function, ::Any) at /Users/johnmulcahy/.julia/packages/Cthulhu/FuE2s/src/Cthulhu.jl:62
 [16] top-level scope at none:0
```

**Comment by vchuravy** [comment] 2019-08-18 10:38
duplicate of #54

**Closed by vchuravy** 2019-08-18 10:38 UTC
